version: "3.8"
services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: datasage
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: infra/Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: datasage
    depends_on:
      - db
  forecast:
    build:
      context: .
      dockerfile: infra/Dockerfile.forecast
    ports:
      - "8000:8000"
  webapp:
    build:
      context: .
      dockerfile: infra/Dockerfile.webapp
    ports:
      - "3001:3001"
    depends_on:
      - api
      - forecast
volumes:
  db-data: